# Generated by Django 6.0.3 on 2026-03-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='derivedmetric',
            new_name='warehouse_d_company_a116b9_idx',
            old_name='warehouse_d_company_7b2c0a_idx',
        ),
        migrations.RenameIndex(
            model_name='fact',
            new_name='warehouse_f_company_ec616d_idx',
            old_name='warehouse_f_company_eb9fa8_idx',
        ),
    ]
