# Generated by Django 6.0.3 on 2026-03-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_warehouse_d_company_7b2c0a_idx_warehouse_d_company_a116b9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='crm_external_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_vertical',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CrmCompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('internal_object_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=512)),
                ('end_user_number', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_class', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=64, null=True)),
                ('global_hq_name', models.CharField(blank=True, max_length=512, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=128, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=512, null=True)),
                ('contract_status', models.CharField(blank=True, max_length=128, null=True)),
                ('vertical', models.CharField(blank=True, max_length=128, null=True)),
                ('display', models.CharField(blank=True, max_length=512, null=True)),
                ('import_label', models.CharField(blank=True, max_length=128, null=True)),
                ('unique_name', models.CharField(blank=True, max_length=512, null=True)),
                ('site_type', models.CharField(blank=True, max_length=64, null=True)),
                ('account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('created_source', models.DateTimeField(blank=True, null=True)),
                ('updated_source', models.DateTimeField(blank=True, null=True)),
                ('has_contract', models.BooleanField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('sec_cik', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('sec_ticker', models.CharField(blank=True, max_length=16, null=True)),
                ('match_status', models.CharField(blank=True, max_length=32, null=True)),
                ('match_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sources', to='warehouse.company')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
