# Generated by Django 6.0.3 on 2026-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_listed_issuer_and_edgar_sync_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listedissuer',
            new_name='warehouse_l_name_b39288_idx',
            old_name='warehouse_l_name_7f3a8b_idx',
        ),
    ]
