# Generated by Django 6.0.3 on 2026-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_rename_warehouse_l_name_7f3a8b_idx_warehouse_l_name_b39288_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgarSecPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(db_index=True, max_length=10)),
                ('kind', models.CharField(choices=[('submissions', 'Submissions'), ('company_facts', 'Company facts')], max_length=32)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'cik'], name='warehouse_e_kind_d773c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('cik', 'kind'), name='warehouse_edgar_sec_payload_cik_kind_uniq')],
            },
        ),
    ]
