# Generated by Django 6.0.6 on 2026-06-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_edgar_sec_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('raw_key', models.CharField(blank=True, max_length=128, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('start_pos', models.IntegerField(default=0)),
                ('end_pos', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.filing')),
            ],
            options={
                'ordering': ['filing_id', 'sequence'],
                'unique_together': {('filing', 'sequence')},
            },
        ),
    ]
