# Generated by Django 6.0.6 on 2026-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_filingdocument_fts_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('char_start', models.IntegerField(default=0)),
                ('char_end', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='warehouse.company')),
                ('filing_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='warehouse.filingdocument')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'source'], name='warehouse_c_company_3f2442_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, max_length=32)),
                ('value', models.CharField(db_index=True, max_length=128)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='warehouse.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system', 'value'), name='external_identifier_uniq')],
            },
        ),
    ]
