# Generated by Django 6.0.6 on 2026-06-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_datasource_contentchunk_externalidentifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('cik', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('external', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_director', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_ten_percent_owner', models.BooleanField(default=False)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, db_index=True, null=True)),
                ('filings_count', models.IntegerField(default=0)),
                ('net_insider_shares', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('source', models.CharField(default='sec_form345', max_length=64)),
                ('source_url', models.CharField(blank=True, max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='warehouse.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='warehouse.person')),
            ],
            options={
                'ordering': ['-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('person', 'company'), name='leadership_person_company_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StakeholderAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('orientation_index', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('method_version', models.CharField(default='1.0', max_length=16)),
                ('caveats', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_assessments', to='warehouse.company')),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('company', 'period_end', 'method_version'), name='stakeholder_assessment_uniq')],
            },
        ),
    ]
