# Generated by Django 6.0.6 on 2026-06-16 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_person_leadershipposition_stakeholderassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('initiatives', models.JSONField(blank=True, default=list)),
                ('quotes', models.JSONField(blank=True, default=list)),
                ('direction', models.TextField(blank=True)),
                ('used_sources', models.JSONField(blank=True, default=list)),
                ('backend', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_analyses', to='warehouse.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='warehouse_l_company_aa6d78_idx')],
            },
        ),
    ]
