# Generated by Django 6.0.3 on 2026-03-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seriesobservation',
            new_name='public_data_series__d7ef06_idx',
            old_name='public_data_series_i_7a1b2c_idx',
        ),
    ]
